DROP TABLE IF EXISTS species;

CREATE TABLE species(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name TEXT NOT NULL,
type TEXT NOT NULL,
extinct BOOLEAN 
);

DROP TABLE IF EXISTS animals;

CREATE TABLE animals(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    animal TEXT NOT NULL,
    diet TEXT NOT NULL,
    species_id BIGINT
)