DROP TABLE IF EXISTS species CASCADE;
DROP TABLE IF EXISTS animals;

CREATE TABLE species(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name TEXT NOT NULL,
type TEXT NOT NULL,
extinct BOOLEAN 
);


CREATE TABLE animals(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    animal TEXT NOT NULL,
    diet TEXT NOT NULL,
    species_id BIGINT NOT NULL REFERENCES species(id)
)